wandb_version: 1

weights:
  desc: null
  value: ./runs/train/NPS/image_size_1280_temporal_YOLO5l_5_frames_NPS_end_to_end_skip_0/weights/last.pt
cfg:
  desc: null
  value: ./models/yolov5l.yaml
data:
  desc: null
  value: ./data/USVID.yaml
hyp:
  desc: null
  value:
    lr0: 0.0032
    lrf: 0.12
    num_frames: 5
    skip_rate: 0
    momentum: 0.843
    weight_decay: 0.00036
    warmup_epochs: 2.0
    warmup_momentum: 0.5
    warmup_bias_lr: 0.05
    box: 0.07
    cls: 0.18
    cls_pw: 0.631
    obj: 0.15
    obj_pw: 0.911
    iou_t: 0.2
    anchor_t: 3
    fl_gamma: 0.0
    hsv_h: 0.4
    hsv_s: 0.3
    hsv_v: 0.5
    degrees: 0.2
    translate: 0.0
    scale: 0.4
    shear: 0.0
    perspective: 0.0
    flipud: 0.0
    fliplr: 0.5
    mosaic: 1.0
    mixup: 0.2
    double_mixup: 0.0
    copy_paste: 0.0
    frame_wise: 1
epochs:
  desc: null
  value: 80
batch_size:
  desc: null
  value: 1
imgsz:
  desc: null
  value: 1024
rect:
  desc: null
  value: false
resume:
  desc: null
  value: false
nosave:
  desc: null
  value: false
noval:
  desc: null
  value: false
noautoanchor:
  desc: null
  value: false
evolve:
  desc: null
  value: null
bucket:
  desc: null
  value: ''
cache:
  desc: null
  value: null
image_weights:
  desc: null
  value: false
device:
  desc: null
  value: ''
multi_scale:
  desc: null
  value: false
single_cls:
  desc: null
  value: false
adam:
  desc: null
  value: true
sync_bn:
  desc: null
  value: false
workers:
  desc: null
  value: 8
project:
  desc: null
  value: ./runs/train/testUSVID
name:
  desc: null
  value: visualization_5_frames
exist_ok:
  desc: null
  value: true
quad:
  desc: null
  value: false
linear_lr:
  desc: null
  value: false
label_smoothing:
  desc: null
  value: 0.0
patience:
  desc: null
  value: 100
freeze:
  desc: null
  value: 0
save_period:
  desc: null
  value: -1
local_rank:
  desc: null
  value: -1
entity:
  desc: null
  value: null
upload_dataset:
  desc: null
  value: false
bbox_interval:
  desc: null
  value: -1
artifact_alias:
  desc: null
  value: latest
save_dir:
  desc: null
  value: runs/train/testUSVID/visualization_5_frames
_wandb:
  desc: null
  value:
    python_version: 3.8.19
    cli_version: 0.16.6
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1714120467.0
    t:
      1:
      - 1
      - 37
      - 41
      - 55
      2:
      - 1
      - 5
      - 37
      - 41
      - 49
      - 53
      - 55
      - 63
      - 80
      3:
      - 13
      - 16
      - 23
      4: 3.8.19
      5: 0.16.6
      8:
      - 5
      13: linux-x86_64
data_dict:
  desc: null
  value:
    path: /data1/jiahaoguo/dataset/UAVTOD_1
    train: /data1/jiahaoguo/dataset/UAVTOD_1/images
    val: /data1/jiahaoguo/dataset/UAVTOD_1/images
    test: /data1/jiahaoguo/dataset/UAVTOD_1/images
    annotation_path: /data1/jiahaoguo/dataset/UAVTOD_1
    annotation_train: /data1/jiahaoguo/dataset/UAVTOD_1/all/yolo
    annotation_val: /data1/jiahaoguo/dataset/UAVTOD_1/all/yolo
    annotation_test: /data1/jiahaoguo/dataset/UAVTOD_1/all/yolo
    video_root_path: /data1/jiahaoguo/dataset/UAVTOD_1
    video_root_path_train: /data1/jiahaoguo/dataset/UAVTOD_1/all/yolo/train.txt
    video_root_path_val: /data1/jiahaoguo/dataset/UAVTOD_1/all/yolo/test.txt
    video_root_path_test: /data1/jiahaoguo/dataset/UAVTOD_1/all/yolo/test.txt
    nc: 8
    names:
    - CarCrowd
    - bicycle
    - bicycleCrowd
    - car
    - ignore
    - people
    - peopleCrowd
    - static_peoplebicycle
